services:
  - type: web
    name: tex-tailor-backend
    env: docker
    plan: free
    healthCheckPath: /health
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: MONGODB_ATLAS_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OLLAMA_BASE_URL
        sync: false
      - key: NODE_ENV
        value: "production"
      - key: NODE_VERSION
        value: "18"
      - key: PYTHON_VERSION
        value: "3.10"
