import express from 'express'
import path from 'path'
import fs from 'fs/promises'
import { fileURLToPath } from 'url'
import archiver from 'archiver'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const router = express.Router()

// Download generated files
router.get('/:jobId/:fileType', async (req, res) => {
  try {
    const { jobId, fileType } = req.params
    const tempDir = path.join(__dirname, '../../temp', jobId)
    
    // Map file types to actual filenames
    const fileMap = {
      'resume': 'Conner_Jordan_Software_Engineer.tuned.pdf',
      'cover-letter': 'Conner_Jordan_Cover_Letter.tuned.pdf',
      'resume-tex': 'Conner_Jordan_Software_Engineer.tuned.tex',
      'cover-letter-tex': 'Conner_Jordan_Cover_Letter.tuned.tex',
      'edits': 'edits.json'
    }
    
    const filename = fileMap[fileType]
    if (!filename) {
      return res.status(400).json({ message: 'Invalid file type' })
    }
    
    const filePath = path.join(tempDir, filename)
    
    try {
      await fs.access(filePath)
      
      // Set appropriate headers
      let contentType = 'application/octet-stream'
      if (filename.endsWith('.pdf')) {
        contentType = 'application/pdf'
      } else if (filename.endsWith('.tex')) {
        contentType = 'text/plain'
      } else if (filename.endsWith('.json')) {
        contentType = 'application/json'
      }
      res.setHeader('Content-Type', contentType)
      res.setHeader('Content-Disposition', `attachment; filename="${filename}"`)
      
      // Stream the file
      const fileStream = await fs.readFile(filePath)
      res.send(fileStream)
      
    } catch (error) {
      res.status(404).json({ message: 'File not found' })
    }
    
  } catch (error) {
    console.error('Download error:', error)
    res.status(500).json({ message: error.message })
  }
})

// Download all files as a zip
router.get('/:jobId/zip/all', async (req, res) => {
  try {
    const { jobId } = req.params
    const tempDir = path.join(__dirname, '../../temp', jobId)
    
    // Check if job directory exists
    try {
      await fs.access(tempDir)
    } catch (error) {
      return res.status(404).json({ message: 'Job not found' })
    }
    
    // List of files to include in the zip
    const filesToInclude = [
      { 
        filename: 'Conner_Jordan_Software_Engineer.tuned.pdf',
        displayName: 'Resume.pdf'
      },
      { 
        filename: 'Conner_Jordan_Cover_Letter.tuned.pdf',
        displayName: 'Cover_Letter.pdf'
      },
      { 
        filename: 'Conner_Jordan_Software_Engineer.tuned.tex',
        displayName: 'Resume.tex'
      },
      { 
        filename: 'Conner_Jordan_Cover_Letter.tuned.tex',
        displayName: 'Cover_Letter.tex'
      },
      { 
        filename: 'edits.json',
        displayName: 'Edit_Details.json'
      },
      { 
        filename: 'job-description.txt',
        displayName: 'Job_Description.txt'
      }
    ]
    
    // Check which files actually exist
    const existingFiles = []
    for (const file of filesToInclude) {
      try {
        const filePath = path.join(tempDir, file.filename)
        await fs.access(filePath)
        existingFiles.push(file)
      } catch (error) {
        console.log(`File not found: ${file.filename}`)
      }
    }
    
    if (existingFiles.length === 0) {
      return res.status(404).json({ message: 'No files found for this job' })
    }
    
    // Set headers for zip download
    const zipFilename = `tex-tailor-results-${jobId}.zip`
    res.setHeader('Content-Type', 'application/zip')
    res.setHeader('Content-Disposition', `attachment; filename="${zipFilename}"`)
    
    // Create zip archive
    const archive = archiver('zip', {
      zlib: { level: 9 } // Maximum compression
    })
    
    // Pipe archive to response
    archive.pipe(res)
    
    // Add files to archive
    for (const file of existingFiles) {
      const filePath = path.join(tempDir, file.filename)
      archive.file(filePath, { name: file.displayName })
    }
    
    // Add a README file with job information
    const readmeContent = `Tex-Tailor Generated Files

Job ID: ${jobId}
Generated: ${new Date().toISOString()}

Files included:
${existingFiles.map(f => `- ${f.displayName}`).join('\n')}

Instructions:
1. Resume.pdf - Your customized resume (ready to submit)
2. Cover_Letter.pdf - Your customized cover letter (ready to submit)
3. Resume.tex - LaTeX source code for the resume (for editing)
4. Cover_Letter.tex - LaTeX source code for the cover letter (for editing)
5. Edit_Details.json - Detailed information about all changes made
6. Job_Description.txt - The original job description you provided

You can edit the .tex files and recompile them using any LaTeX editor.
The .json file contains detailed information about how the AI customized your documents.

Generated by Tex-Tailor - AI-powered resume customization
`
    
    archive.append(readmeContent, { name: 'README.txt' })
    
    // Finalize the archive
    await archive.finalize()
    
  } catch (error) {
    console.error('Zip download error:', error)
    res.status(500).json({ message: error.message })
  }
})

export default router